FROM tensorflow/tensorflow:1.13.0rc2-gpu-py3-jupyter

RUN apt-get update \
 && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget

RUN wget https://bootstrap.pypa.io/get-pip.py \
&& python3 get-pip.py \
&& rm get-pip.py

WORKDIR /root
ADD requirements_jupyter.txt /root/
RUN pip3 --no-cache-dir install -r requirements_jupyter.txt \
&& rm requirements_jupyter.txt
